core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('store/', include('store.urls')),
    path('user/', include('account.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'),
         name="ck_editor_5_upload_file"),
    path("__debug__/", include('debug_toolbar.urls')),
    re_path(r"^static(?P<path>.*)$", serve,
            {"document_root": settings.STATIC_ROOT}),
    re_path(r"^media(?P<path>.*)$", serve,
            {"document_root": settings.MEDIA_ROOT}),
]
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views


urlpatterns = [
    path('', views.product_list, name='store'),
    # path(r'^categories/$', views.product_list, name = "products_by_category"),
    path('category/<slug:category_slug>/',
         views.product_list, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_detail"),
    path('filter-data', views.filter_data, name='filter_data'),
    path('search/', views.search, name='search'),
    path("wishlist/", views.wishlist, name="wishlist"),
    path('toggle-wishlist/', views.toggle_wishlist, name='toggle-wishlist'),    
    path('remove-from-wishlist/', views.remove_from_wishlist, name="remove_from_wishlist")
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from slugify import slugify
from category.models import Category
from mptt.models import TreeForeignKey
from account.models import Account


class Product(models.Model):
    product_name = models.CharField(max_length=500)
    product_slug = models.SlugField(null=False, blank=False)
    product_price = models.PositiveIntegerField()
    category = TreeForeignKey(Category, on_delete=models.CASCADE)
    product_stock = models.IntegerField(default=1, unique =False)
    product_description = models.TextField(null=True, blank=True)
    product_cleaning = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
                    
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.product_slug])

    def price_with_tax(self):
        return str(self.product_price + self.product_price*20/100)

    def __str__(self):
        return self.product_slug

    
    def number(self):
        count = Variation.objects.count()
        if count == 0:
            return 1
        else:
            last_object = Variation.objects.order_by('-id')[0]
            return last_object.id + 1
    

class Color(models.Model):
    name=models.CharField(max_length=100, unique=True)
    colorCode=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Size(models.Model):
    size=models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return str(self.size)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_number = models.PositiveBigIntegerField(unique=False, null=True, blank=True)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)
    created_date = models.DateField(auto_now=True)


    def __str__(self):
        return self.product.product_name

class VariationImages(models.Model):
    title = models.CharField(max_length=500, blank=True, null = True)
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    variation_image = models.ImageField(upload_to='static/variation_images/', verbose_name=("variation_image"))
    variation_image_slug = models.SlugField(null=True, blank=True)
    def __str__(self):
        return str(self.title)  # on met str(...) pour convertir en string

    
    
class Wishlist(models.Model):
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    product =models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "wishlists"
    def __str__(self):
        return self.product.product_name
   
class Photo(models.Model):
    title = models.CharField(max_length=500, blank=True, null = True)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='photos')
    # photo_name = models.ImageField(upload_to='stactic/photos/', verbose_name=("image"))
    product_image = models.ImageField(upload_to='static/photos/', verbose_name=("image"))
    photo_slug = models.SlugField(null=True, blank=True)
    def __str__(self):
        return str(self.product_image)  # on met str(...) pour convertir en string

    @property
    def photoURL(self):
        try:
            url = self.photo_name.url
        except:
            url = ''
        print('URL :', url)
        return

store/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from carts.models import CartItem
from carts.views import _cart_id
from category.models import Category
from store.models import Color, Photo, Product, Size, Variation, VariationImages, Wishlist
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string


def product_list(request, category_slug=None, product_slug=None):
    wishlisted_list = []
    if request.user.is_authenticated:
        wishlisted_list = list(Wishlist.objects.filter(user_id=request.user).values_list(
            'product_id', flat=True).order_by('product_id'))

    category = None
    products = None
    categories = Category.objects.all()
    # for printint only the parents
    parents = Category.objects.filter(parent=None)
    # End for printint only the parents

    # Start filter by product variation
    colors = Variation.objects.distinct().values(
        'color__name', 'color__id', 'color__colorCode')
    sizes = Variation.objects.distinct().values('size__size', 'size__id')
    # End filter by product variation

    # start Size color and filter
    SizeId = request.GET.get('sizeID')
    ColorId = request.GET.get('colorID')
    # End Size color and filter
    # Start sortby
    sort_by = request.GET.get("sort", "l2h")
    # End sortby
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sub_categories = category.get_descendants(include_self=True)
        products = Product.objects.filter(category__in=sub_categories)
     # start Size color and filter
    elif SizeId:
        products = Product.objects.filter(
            variation__size__id__in=SizeId).distinct()
    elif ColorId:
        products = Product.objects.filter(
            variation__color__id__in=ColorId).distinct()
    # End Size color and filter
    # Start sortby
    elif sort_by == "l2h":
        products = Product.objects.filter(
            is_active=True).order_by('product_price')
    elif sort_by == "h2l":
        products = Product.objects.filter(
            is_active=True).order_by('-product_price')
    # end sort by
    # start Size color and filter
    else:
        products = Product.objects.all().filter(is_active=True)

    return render(request,
                  'store/store.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'parents': parents,
                   # 'productx': productx,
                   'sizes': sizes,
                   'colors': colors,
                   'wishlisted_list': wishlisted_list
                   })


def product_detail(request, category_slug, product_slug):
    try:
        # product=Product.objects.get(id=id)
        # Retrieve the single product instance
        single_product = Product.objects.get(
            category__slug=category_slug, product_slug=product_slug)
        # details images
        variations = Variation.objects.filter(product=single_product)
        # if item is already in the cart
        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(request), product=single_product)
        # colors and sizes
        colors = Variation.objects.filter(product=single_product).values(
            'color__id', 'color__name', 'color__colorCode').distinct()
        sizes = Variation.objects.filter(product=single_product).values(
            'size__id', 'size__size', 'color__id').distinct()

    except Exception as e:
        raise
    context = {
        'single_product': single_product,
        'variations': variations,
        'in_cart': in_cart,
        'colors': colors,
        'sizes': sizes,
        # 'data':product
    }
    return render(request, 'store/product_detail.html', context)

# filter data


def filter_data(request):
    colors = request.GET.getlist('color[]')
    sizes = request.GET.getlist('size[]')
    allProducts = Product.objects.all().order_by('-id').distinct()
    if len(colors) > 0:
        allProducts = allProducts.filter(
            variation__color__id__in=colors).distinct()
    if len(sizes) > 0:
        allProducts = allProducts.filter(
            variation__size__id__in=sizes).distinct()
    t = render_to_string('ajax/product-list.html', {'data': allProducts})
    return JsonResponse({'data': t})


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created').filter(
                Q(product_description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request,  'store/store.html', context)


@login_required
# My Wishlist
def wishlist(request):
    wishlist = Wishlist.objects.filter(user=request.user).order_by('-id')
    context = {
        "wishlist": wishlist
    }
    return render(request, "account/dashboard/wishlist.html", context)


def toggle_wishlist(request):
    if not request.user.is_authenticated:
        return JsonResponse({'error': 'Authentication required'}, status=401)

    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, id=product_id)

    wishlist_item, created = Wishlist.objects.get_or_create(
        user=request.user, product=product)
    if not created:
        # The product is already in the wishlist, so we remove it
        wishlist_item.delete()
        action = 'removed'
    else:
        action = 'added'

    # Count current items in the wishlist after action
    wishlist_count = Wishlist.objects.filter(user=request.user).count()

    return JsonResponse({'status': action, 'wishlist_count': wishlist_count})


def remove_from_wishlist(request):
    pid = request.GET['id']
    wishlist = Wishlist.objects.filter(user=request.user).count()
    wishlist_id = Wishlist.objects.get(id=pid)
    delete_product = wishlist_id.delete()
    context = {
        "bool": True,
        'wishlist': wishlist
    }

    t = render_to_string('store/async/wishlist_list.html', context)

    return JsonResponse({'data': t, 'all_wishlist': wishlist})

templates/store/product_detail.html
{% extends '../base.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>
<link
  rel="stylesheet"
  href=" {% static 'assets/styles/product-details/product-details.css' %}"
/>
<!-- Jquery part -->
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"
></script>
<!-- End Jquery part -->
<section class="main-details-container">
  <!-- Start Left details elements -->

  <div class="left-details-container">
    <div class="swiper mySwiper">
      <div class="swiper-wrapper">
        {% for variation in variations %} 
        {% for image in variation.variationimages_set.all %}
        <img
          class="swiper-slide {% if forloop.parentloop.first and forloop.first %} active {% endif %}"
          src="{{ image.variation_image.url }}"
          alt="{{ image.title }}"
        />
        {% endfor %} {% endfor %}
      </div>
      <div class="swiper-button-next swiper-arrow"></div>
      <div class="swiper-button-prev swiper-arrow"></div>
    </div>
  </div>
  <!-- End Left details elements -->

  <!-- Right details elements -->
  <div class="right-details-container">
    <div class="product-name">{{single_product.product_name}}</div>
    <div class="form-container">
      <form action="{% url 'add_to_cart' single_product.id %}" method="POST">
        {% csrf_token %}
        <ul>
          <li>
            
            {% if messages %}
            <div class="alert" role="alert" id="cart-message">
                {% for message in messages %}
                    {% if 'cart_success' in message.tags or 'cart_error' in message.tags %}
                        <div class="{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

          </li>
          <li class="variant-colors">
            <div class="color-choice">
              {% for color in colors %}
              <span>{{color.color__name | capfirst }}</span>
              {% endfor %}
            </div>
            <div class="color-container">
              {% for color in colors %}
              <div class="colorbox">
                <input
                  required
                  class="blackinput choose-color"
                  type="radio"
                  name="color"
                  id="color"
                  data-color="{{color.color__id}}"
                  value="{{color.color__id}}"
                />

                <button
                  type="button"
                  class="choose-color"
                  data-color="{{color.color__id}}"
                  style="background-color: {{color.color__colorCode}}"
                ></button>
              </div>
              {% endfor %}
            </div>
          </li>

          <!-- Size -->

          <li class="variant-size">
            <div class="size-container">
              {% for size in sizes %}
              <div class="sizebox">
                <input
                  required
                  class="size_input choose-size color{{size.color__id}}"
                  type="radio"
                  name="size"
                  id="size"
                  value="{{ size.size__id}}"
                />
                <button
                  type="button"
                  class="choose-size color{{size.color__id}}"
                >
                  {{size.size__size | capfirst }}
                </button>
              </div>
              {% endfor %}
            </div>
          </li>

          <!-- Select colors and sizes -->

          <li class="submit-button">
            <div>
              <input type="hidden" class="product-id" value="{{data.id}}" />
              <input
                type="hidden"
                class="product-name"
                value="{{data.product_name}}"
              />
            </div>
            {% if single_product.stock <= 0 %}
            <button
              class="add-to-cart"
              type="button"
              data-index="{{data.id}}"
              id="addToCartBtn"
            >
              <div class="submit-left">
                <span class="material-symbols-outlined"> shopping_bag </span>
                <span class="add-button"> Product out of</span>
              </div>
              <div class="submit-right">
                <span class="price-button">
                  <p class="price product-price">
                    {{single_product.product_price }}
                  </p>
                </span>
              </div>
            </button>
            {% else %}
            <button class="add-to-cart" type="submit" id="addToCartBtn">
              <div class="submit-left">
                <span class="material-symbols-outlined"> shopping_bag </span>
                <span class="add-button"> Add</span>
              </div>
              <div class="submit-right">
                <span class="price-button">
                  <p class="price product-price">
                    {{single_product.product_price }} Eur
                  </p>
                </span>
              </div>
            </button>
            {% endif %}
          </li>
        </ul>
      </form>
    </div>
    <div class="details-cleaning">
      <ul class="tabs">
        <li id="details-linkId" onmouseover="openDetails()" class="details">
          Details
        </li>
        <li id="cleaning-linkId" onmouseover="openCleaning()" class="cleaning">
          Cleaning
        </li>
      </ul>
      <ul class="tabs-contents">
        <li id="detailsId" class="tabs-details-text" id="page_content">
          <p class="details-text">{{single_product.product_description}}</p>
        </li>

        <li id="cleaningId" class="tabs-cleaning-text" id="page_content">
          <p class="cleaning-text">{{single_product.product_cleaning}}</p>
        </li>
      </ul>
    </div>
  </div>
  <!-- End Right details elements -->
</section>
<!-- Start Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script>
  var swiper = new Swiper(".mySwiper", {
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
<!-- add to cart  -->

<script>
  $(document).ready(function () {
    // Product Variation
    $(".choose-size").hide();

    // Show size according to selected color
    $(".choose-color").on("click", function () {
      $(".choose-size").removeClass("active");
      $(".choose-color").removeClass("focused");
      $(this).addClass("focused");

      var _color = $(this).attr("data-color");

      $(".choose-size").hide();
      $(".color" + _color).show();
      $(".color" + _color)
        .first()
        .addClass("active");
    });
    // End

    // Show the first selected color
    $(".choose-color").first().addClass("focused");
    var _color = $(".choose-color").first().attr("data-color");
    var _price = $(".choose-size").first().attr("data-price");

    $(".color" + _color).show();
    $(".color" + _color)
      .first()
      .addClass("active");

    // End
  });
  // End Document.Ready
</script>
<!-- End add to cart  -->

<!-- End Swiper JS -->

<!-- Details and cleaning script -->
<script>
  var details = document.getElementById("detailsId");
  var cleaning = document.getElementById("cleaningId");
  var detailsLink = document.getElementById("details-linkId");
  var cleaningLink = document.getElementById("cleaning-linkId");

  function openDetails() {
    details.style.opacity = "1";
    cleaning.style.opacity = "0";
    detailsLink.style.borderBottom = "1px solid black";
    cleaningLink.style.borderBottom = "1px solid white";
  }

  function openCleaning() {
    details.style.opacity = "0";
    cleaning.style.opacity = "1";
    cleaningLink.style.borderBottom = "1px solid black";
    detailsLink.style.borderBottom = "1px solid white";
  }
</script>
<!-- End details and cleaning script -->

<!-- Colors variants scripts -->
<!-- Colors variants scripts -->
{% endblock %}

templates/store/store.html
{% extends '../base.html' %} {% load static %} {% block title %} 
{% if category %} Product for {{category.name}} {% else %} All products in the store {% endif %} 
{% endblock %} 
{% block content %}
<link rel="stylesheet" href=" {% static 'assets/styles/store/store.css' %}" />
<link
  rel="stylesheet"
  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
/>
<!--  Js Static file  -->
<script type="text/javascript" src="{% static 'assets/js/product_filter.js' %}"></script>

<section class="top-content"></section>

<div class="categories-and-filters">
  {% if category %}
  <ul class="category-parents">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'store' %}">All</a></li>
    <li class="active-cat">{{category.name}}</li>
  </ul>
  {% else %}
  <ul class="category-parents">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li class="active-all">All</li>
    {% for cat in parents %}
    <li>
      <a href="{% url 'products_by_category' cat.slug %}">{{cat.name}}</a>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <ul class="filter-contents">
    <li class="filter-element">
      <a id="filter-modal-link-colorid" class="filter-modal-link"
        >Colors
        <i class="bx bxs-chevron-down filter__dropdown__icon"></i>
      </a>
      {% include './include/color_modal.html' %}
    </li>
    <!-- Start filter size -->
    <li class="filter-element">
      <a id="filter-modal-link-sizeid" class="filter-modal-link"
        >Size
        <i class="bx bxs-chevron-down filter__dropdown__icon"></i>
      </a>
      {% include './include/size_modal.html' %}
    </li>
    <!-- end filter size -->
    <li class="filter-element">
      <a id="filter-modal-link-sortbyid" class="filter-modal-link"
        >Sort by
        <i class="bx bxs-chevron-down filter__dropdown__icon"></i>
      </a>
      {% include './include/sort_modal.html' %}
    </li>
  </ul>
</div>
{% include './include/store-gallery.html' %}

<!-- 
<script type="text/javascript">
  $(document).ready(function () {
    $(".ajaxLoader").hide();
    $(".filter-checkbox").on("click", function(e) {
      e.preventDefault();
      var _filterObj={};
      $(".filter-checkbox").each(function (index,ele) {
        var _filterVal = $(this).val();
        var _filterKey = $(this).data("filter");
        _filterObj[_filterKey] = Array.from(document.querySelectorAll("input[data-filter=" + _filterKey + "]:checked")
        ).map(function(el){
          return el.value;
        });
      });

      var attr_id = $(this).attr("attr_id");
      var action_url = $(this).attr("action_url");
  
      // Run Ajax
  
      $.ajax({
        url: action_url,
        data:{ attr_id: attr_id },
        success: function (result) {
          console.log("Success");
        },
        error: function () {
          console.log("Please login");
        },
      });
    });
  });
  
</script> -->
{% endblock %}